### ISSUE TITLE
Fixed todo in User.py line 159/160

### ISSUE THREAD

**Issue by 11Tuvork28** [Skelmis/DPY-Anti-Spam#10]
So the todo was "TODO Figure out why the logic likes having +1 of the actual count
before it decides its time to actually punish the user properly".

The problem is that we set  self.duplicateCounter  to 0 and we can't see if a message is a duplicate until we have another message/duplicate. If we have 2 duplicates we can set the counter to 1 but after the 5th duplicate its at 4 and not at 5.

So my solution is to either set the counter to one or subtract 1 in every check against "warnThreshold", or add 1 to counter at every check.
 For performance reasons I would prefer to initialize the  duplicateCounter with 1 and if its ever needed to look the user object up via a command then just subtract 1 from the duplicateCounter.

I don't want to make a decision here so its up to you what you do :)

**Comment by Skelmis** [comment]
Sorry for only just noticing this, I will look into it further tonight during further punishment implementation and decide on a course of action.

**Comment by Skelmis** [comment]
*Note, given its preset to 1 now rather then 0 and that needs to be kept in mind. Im looking into possibly turning it into a get/set or something with a public/private setup to remove the need to worry about the actual value outside of the class*

**Comment by 11Tuvork28** [comment]
Yeah as I'm working with your project in my bot maybe I come  up with a nice solution like that or something better who knows and no problem regarding the time offset of you noticing that. Hope it was helpful anyway

**Comment by Skelmis** [comment]
Should be resolved now, and I appreciate your feedback in issues and pull requests :) 
Its always helpful, keep it up! 👍
