### ISSUE TITLE
More Options - Feature Tracker

### ISSUE THREAD

**Issue by Skelmis** [Skelmis/DPY-Anti-Spam#14]
Currently the package is very set in its ways, some people may just want to warn users there spamming without repercussions.
~~`Add a mode to just warn only`~~

~~Another thing, there can be an option for whether the bot should cleanup messages it classes as spam, i.e. attempt to delete them~~

Feel free to add more as we go, this can be a 'feature tracker' of sorts

**Comment by Skelmis** [comment]
#12 applies under this as well

**Comment by Skelmis** [comment]
Further options for handling `mass pings`, given a configurable amount of pings. If this is exceeded then punish

**Comment by 11Tuvork28** [comment]
Some ideas:
- per channel write cooldown/timeout depending on the current msg/s 
- temporarily lockdowns per channel or complete guild 
- a list of ignored channels and or users. Maybe via decorators

**Comment by Skelmis** [comment]
In response to the above.
Per channel cooldowns could be a feature for 1.1 I feel, same for automatic lockdowns

A list of ignored channels/users relates to 1.0 and is already somewhat implemented and I will push a commit with further changes and a public interface for updating them.

**Comment by Skelmis** [comment]
Add in the ability to use templating for anything in `self.options`

**Comment by Skelmis** [comment]
More customizable options for message templating. Basically any string sent to the user should be able to be custom

**Comment by Skelmis** [comment]
Per_channel_spam as a boolean option so it's not just the overall guild spam

**Comment by Skelmis** [comment]
> Per_channel_spam as a boolean option so it's not just the overall guild spam

This requires rewriting the User.propagate method, more technically the way duplicates are counted so it can by dynamic rather then just per User. So not doing it now

**Comment by Skelmis** [comment]
per_guild spam rather then just per_user

**Comment by Skelmis** [comment]
> Some ideas:
> 
> * per channel write cooldown/timeout depending on the current msg/s
> * temporarily lockdowns per channel or complete guild
> * a list of ignored channels and or users. Maybe via decorators

This is now onto the user with the implementation of custom punishments.

**Comment by Skelmis** [comment]
Closing for now
