### ISSUE TITLE
Installing the package does not draw its prerequisites

### ISSUE THREAD

**Issue by Diakon5** [Skelmis/DPY-Anti-Spam#19]
I decided to include some spam protection following a recent raid, and after installing the library and following the quickstart guide, I got a warning "module "fuzzywuzzy" not found". I had to install it manually... Libraries most often check for their dependencies and install them automatically when needed, this should too.

**Comment by Skelmis** [comment]
I agree with your comments, it should install what is required. I was not aware through my testing it had not. I will get this fixed asap.

**Comment by Skelmis** [comment]
I am hoping this has resolved the issue, I am unable to test until my `pip` recognizes the newer version.
