### ISSUE TITLE
Exception information differing from desired variable type in AntiSpamHandler

### ISSUE THREAD

**Issue by Diakon5** [Skelmis/DPY-Anti-Spam#22]
![image](https://user-images.githubusercontent.com/72417806/99703590-926d5880-2a97-11eb-8dc8-d7510ae83bfb.png)
Sending an Int to messageDuplicateAccuracy raises an error that tells me I should... pass an int to it. In reality, the class expects a float. This error occurs in ignoreBots too:
![image](https://user-images.githubusercontent.com/72417806/99704121-3a832180-2a98-11eb-8a85-268fdf579c4f.png)

**Comment by Skelmis** [comment]
Haha, that's on me for copying, pasting and forgetting. Will merge the pr addressing the issue tomorrow. Cheers for bringing it up
