### ISSUE TITLE
Handler attempts to propagade messages in Direct Message channel

### ISSUE THREAD

**Issue by Diakon5** [Skelmis/DPY-Anti-Spam#23]
Testing one of the first commands that can only be used in direct message channel. Using the command raises "AttributeError: 'User' object has no attribute 'roles'"  exception, but otherwise doesn't prevent the command from executing. Can be circumvented manually, but should be handled by the library automatically.

**Comment by Skelmis** [comment]
Its funny actually, I noticed this and fixed it myself during my last batch of commits just over 28 hours ago. Its not quite on pip yet however, so you will have to install via git.

It has been fixed however, and thank you for making an issue for it! Ill update pip this weekend with the new features n fixes
