### ISSUE TITLE
Kick count shows incorrectly.

### ISSUE THREAD

**Issue by Codeize** [Skelmis/DPY-Anti-Spam#30]
**Description**
When the user is kicked, the kick count appears incorrectly. -1 of what the actual figure.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spam to the kick threshold.
2. Look at the kick count. It shows -1 of what it should be.

**Expected behaviour**
It should show correctly.

**Screenshots**
The bug : ![Screenshot_20201129-161041_Discord.jpg](https://user-images.githubusercontent.com/63158950/100547247-9babb180-325d-11eb-994a-dc4100ebdb6e.jpg)

**Enviroment**
 - Pacakge Version: 0.3

**Comment by Skelmis** [comment]
This is also prevalent in warn_count afaim
