### ISSUE TITLE
Migrate away from Travis Ci since there essentially dropping support for OSS 

### ISSUE THREAD

**Issue by Skelmis** [Skelmis/DPY-Anti-Spam#35]
Get a total of 1000 minutes of build time now, total. That's roughly 333 builds, heaps you might say! Except as far as I know thats over your account, not per repo. Even if it was per repo, 333 builds would last a few months then migration is required anyway. On days of active development, there might be around 5 builds run. Etc. You get the picture.

The alternative is Github Actions and is something to be looked into before the 31st December

**Comment by 11Tuvork28** [comment]
What about [Jenkins](https://www.jenkins.io/)? Can be selfhosted and I guess you already have a vps so Jenkins could be ideal for the project :)

**Comment by Skelmis** [comment]
Hahaha, this is actually quite funny since I was discussing this with a friend today who used jenkins at his workplace and said the same thing. So it's definitely something I'll look into

**Comment by 11Tuvork28** [comment]
Lol I can read minds hahah, the reason I came up with it is that I'm setting gitlab and jenkins on vps for my independent workflow.

**Comment by Skelmis** [comment]
I might need to scale my vps, however that's fine and otherwise it'd be a good learning curve. Can even chuck it behind nginx so it plays nicely with my current setup although this is likely going to be something for a few weeks time as I'm quite busy rn

**Comment by 11Tuvork28** [comment]
Sounds solid and yeah something like this eats through time like Chrome eats through ram :D
